"""empty message

Revision ID: a21e8fe7c139
Revises: e5a7fd3a3f2d
Create Date: 2023-03-07 13:29:12.156267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21e8fe7c139'
down_revision = 'e5a7fd3a3f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phonebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('mobile_number', sa.String(length=120), nullable=True),
    sa.Column('office_number', sa.String(length=128), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phonebook', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phonebook_first_name'), ['first_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_phonebook_last_name'), ['last_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_phonebook_mobile_number'), ['mobile_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_phonebook_office_number'), ['office_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phonebook', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phonebook_office_number'))
        batch_op.drop_index(batch_op.f('ix_phonebook_mobile_number'))
        batch_op.drop_index(batch_op.f('ix_phonebook_last_name'))
        batch_op.drop_index(batch_op.f('ix_phonebook_first_name'))

    op.drop_table('phonebook')
    # ### end Alembic commands ###
